class Recipe {
  final String title;
  final List<String>  description;
  final String imageUrl;
  final List<String> ingredients;

  Recipe({required this.title, required this.description, required this.imageUrl, required this.ingredients});
}

List<Recipe> sampleRecipes = [
  Recipe(
    title: "Chickpeas Tikka ",
    description: ["1. In a large bowl, take boiled chickpeas and add yoghurt, ginger-garlic paste, fenugreek seeds, garam masala, turmeric powder, coriander powder, red chilli powder, chaat masala, black pepper powder, and salt. Mix well until the boiled chickpeas are coated well. Cover the bowl and keep it aside for 30 minutes to 1 hour.",
    "2. In a pan, put some oil/butter, and add ginger-garlic paste to it. Now dump the solid spices into the cooked ginger-garlic paste. After they begin to pop, add chopped onions and cook them until they are translucent.",
    "3. Now put the chopped tomatoes in the pan. Add rest of the spices – cumin powder, garam masala, turmeric powder, soaked cashews, coriander powder, red chilli powder, and salt. Mix well and cover the lid so that the tomatoes become soft and mushy. Switch off the gas burner and let the mixture cool down.",
    "4. In another pan, take some oil/butter and add the marinated chole. Cook them until they start to smell aromatic. Put off the burner.",
    "5. Now, put the onion-tomato paste in a mixer and blend until it becomes smooth like a paste. Be careful that the blender does not overheat because of the hot onion-tomato mix. Keep opening the lid to let off the steam.",
    "6. After the paste is ready, add this to the pan of marinated chickpeas. At this point, you will have to decide the thickness of the gravy. Add one 1.5 cups of water and mix everything. Bring it to boil.",
    "7. Make sure to taste the gravy at this point. Add spices to adjust the taste levels. Now add 1 cup of heavy cream in the chickpea tikka masala. Mix well.",
    "8. Garnish the chickpea tikka masala with coriander and ginger slivers. And voila! your Chickpea Tikka Masala is ready to serve!"],
    imageUrl: "https://www.allrecipes.com/thmb/V4nniUwQwTG-qvjGIWQRtFo2oHc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/7497387-chickpea-tikka-masala-ddmfs_4x3_1791-e0838138030a4b55ac7340027bc2b47f.jpg",
  ingredients: ["2 Cups boiled chole chickpeas",
      "1.5 Cups dahi",
      "yoghurt",
    "2 Tbsp ginger-garlic paste",
    "1 Tbsp methi/fenugreek seeds",
    "2.5 garam masala",
    "1.5 Tbsp haldi/turmeric powder",
    "1.5 Tbsp dhaniya/coriander powder",
    "2 tsp red chilli powder",
    "1 tsp chaat masala"]),
  Recipe(
    title: "Beetroot Halwa",
    description: [ "1. In a wide pan, heat 2 tsp of ghee.",
    "2. Add the skin peel to the pan and sauté for a few minutes.",
    "3. Pour in the milk and cook over low to medium flame for about 15 minutes until the vegetables are thoroughly cooked and soft. ",
    "4. Once the vegetables are cooked, add sugar and mava to the pan.",
    "5. Continue cooking for an additional 5 minutes until the mixture achieves a thick consistency.",
    "6. In a separate pan, sauté the assorted nuts in ghee until they turn a golden colour.",
    "7. Add the remaining ghee, cardamom pods and seeds, as well as the sautéed nuts, to the main mixture.",
    "8. Mix all the ingredients thoroughly. Serve and enjoy the dish while it is warm "],
    imageUrl: "https://c.ndtvimg.com/2023-11/rt2d5vdg_beetroot-halwa_625x300_10_November_23.jpg",
  ingredients: ["300 gms Carrot Skin Peel",
      "300 Beetroot Skin Peel",
      "125 Mava125",
      "Sugar25 ",
      "Desi Ghee",
      "15 Cashewnuts",
      "1 Cardamom Powder",
      "10 Raisin",
      "7 Almond Flakes",
      "50 Milk"]),
  Recipe(
    title: "Dahiwali Toor Dal",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
    "2. Heat ghee in a pan and add ginger-garlic.",
    "3. Saute and add tomato to it. ",
    "4. Add the spices, some salt and cook until it leaves oil. ",
    "5. Add dahi and mix.",
    "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
    "7. Now adjust salt and sugar, crush some kasuri methi and add.",
    "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://c.ndtvimg.com/2023-08/u4lrelqg_dahiwali-toor-dal_625x300_01_August_23.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300gm dal",
        "125 mava",
        "1 Tomato ",
        "Desi Ghee",
        "3 Chilly",
        "1 tsp Cardamom Powder",
        "1 Onion",
        "7 curry leaves",
        "1lr Milk"]),
  Recipe(
    title: "Gulkand Ice Cream",
    description: ["1. Prepare 55 Ml Vanilla Ice Cream, 50 ml Gulkand and 5 ml Roohafza.",
    "2. Mix all ingredients together and keep in refrigerator for 5-6 hours and when well set, scoop out and serve well garnished. "],
    imageUrl: "https://rumkisgoldenspoon.com/wp-content/uploads/2022/05/Gulkand-icecream.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Mango Kulfi",
    description: ["1. To make this kulfi, first we need to boil the milk till it reduces to half its original quantity. Now, add sugar and pista and allow it to cool completely. (Boiling the milk may take around 30–40 minutes, so make sure to keep stirring it occasionally.)",
    "2. Meanwhile, remove the seed of the mango while keeping its shape intact. Remove the top part of the mango and keep it aside for later use. Gently squeeze the mango and use a knife to loosen the pulp around the seed. Pull it out and keep it upright in a cup or glass.",
    "3. Fill these mango shells with the prepared kulfi mixture and put the top part of the mango on it. Freeze for 3 to 4 hours, remove the peel, cut it into slices, and serve chilled."],
    imageUrl: "https://bakewithshivesh.com/wp-content/uploads/2020/04/C7F4525D-BE57-4A88-AA55-5F74746288CF.jpeg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Cinamon French Toast",
    description: [ "1. For the French toast: Grease the baking pan with butter. Tear the bread into chunks, or cut into cubes, and evenly distribute in the pan. Crack the eggs in a big bowl. Whisk together the eggs, milk, cream, granulated sugar, brown sugar and vanilla. Pour evenly over the bread. Cover the pan tightly and store in the fridge until needed (overnight preferably). ",
    "2. For the topping: Mix the flour, brown sugar, cinnamon, salt and some nutmeg in a separate bowl. Stir together using a fork. Add the butter and with a pastry cutter, and mix it all together until the mixture resembles fine pebbles. Store in a re-sealable plastic bag in the fridge. ",
    "3. When you're ready to bake the casserole, preheat the oven to 350 degrees F. Remove the casserole from the fridge and sprinkle the topping over the top. Bake for 45 minutes for a softer, more bread pudding texture or for 1 hour or more for a firmer, crisper texture. ",
    "4. Scoop out individual portions. Top with butter and drizzle with warm pancake syrup and sprinkle with blueberries."],
    imageUrl: "https://www.closetcooking.com/wp-content/uploads/2011/04/CinnamonSwirlFrenchToast500.jpg",
      ingredients: ["4 slices of bread",
      "2 eggs",
      "1/4 cups milk",
      "1 tsp vanilla extract",
      "1/2 tsp cinnamon",
      "2 tbsp peanut butter",
      "2 tbsp Butter"]),
  Recipe(
    title: "Rajasthani Dal",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://c.ndtvimg.com/2023-08/u4lrelqg_dahiwali-toor-dal_625x300_01_August_23.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Peas Masala",
    description: ["1. In a large bowl, take boiled chickpeas and add yoghurt, ginger-garlic paste, fenugreek seeds, garam masala, turmeric powder, coriander powder, red chilli powder, chaat masala, black pepper powder, and salt. Mix well until the boiled chickpeas are coated well. Cover the bowl and keep it aside for 30 minutes to 1 hour.",
      "2. In a pan, put some oil/butter, and add ginger-garlic paste to it. Now dump the solid spices into the cooked ginger-garlic paste. After they begin to pop, add chopped onions and cook them until they are translucent.",
      "3. Now put the chopped tomatoes in the pan. Add rest of the spices – cumin powder, garam masala, turmeric powder, soaked cashews, coriander powder, red chilli powder, and salt. Mix well and cover the lid so that the tomatoes become soft and mushy. Switch off the gas burner and let the mixture cool down.",
      "4. In another pan, take some oil/butter and add the marinated chole. Cook them until they start to smell aromatic. Put off the burner.",
      "5. Now, put the onion-tomato paste in a mixer and blend until it becomes smooth like a paste. Be careful that the blender does not overheat because of the hot onion-tomato mix. Keep opening the lid to let off the steam.",
      "6. After the paste is ready, add this to the pan of marinated chickpeas. At this point, you will have to decide the thickness of the gravy. Add one 1.5 cups of water and mix everything. Bring it to boil.",
      "7. Make sure to taste the gravy at this point. Add spices to adjust the taste levels. Now add 1 cup of heavy cream in the chickpea tikka masala. Mix well.",
      "8. Garnish the chickpea tikka masala with coriander and ginger slivers. And voila! your Chickpea Tikka Masala is ready to serve!"],
    imageUrl: "https://glutenfreecuppatea.co.uk/wp-content/uploads/2019/01/gluten-free-chickpea-tikka-masala-curry-3.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Beetroot Halwa",
    description: [ "1. In a wide pan, heat 2 tsp of ghee.",
      "2. Add the skin peel to the pan and sauté for a few minutes.",
      "3. Pour in the milk and cook over low to medium flame for about 15 minutes until the vegetables are thoroughly cooked and soft. ",
      "4. Once the vegetables are cooked, add sugar and mava to the pan.",
      "5. Continue cooking for an additional 5 minutes until the mixture achieves a thick consistency.",
      "6. In a separate pan, sauté the assorted nuts in ghee until they turn a golden colour.",
      "7. Add the remaining ghee, cardamom pods and seeds, as well as the sautéed nuts, to the main mixture.",
      "8. Mix all the ingredients thoroughly. Serve and enjoy the dish while it is warm "],
    imageUrl: "https://c.ndtvimg.com/2023-11/rt2d5vdg_beetroot-halwa_625x300_10_November_23.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Beef Steak Gravy",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://www.unileverfoodsolutions.com.ph/dam/global-ufs/mcos/SEA/calcmenu/recipes/PH-recipes/red-meats-&-red-meat-dishes/beef-steak-with-peppercorn-gravy/beef-steak-with-peppercorn-gravy-main.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Tuscan Chicken",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://carlsbadcravings.com/wp-content/uploads/2020/07/Tuscan-Chicken-v1-500x375.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Fish Tandoori",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Tandoori_fish.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Club Sandwich",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://images.arla.com/recordid/15F33607-F6D9-4952-B6AA210D3033BF14/club-sandwich1.jpg?format=jpg&width=1200&height=630&mode=crop",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: "Tarrogon Pasta",
    description: ["1. Mix both the dal and boil with salt and turmeric. ",
      "2. Heat ghee in a pan and add ginger-garlic.",
      "3. Saute and add tomato to it. ",
      "4. Add the spices, some salt and cook until it leaves oil. ",
      "5. Add dahi and mix.",
      "6. Add dahi, mix and let it simmer for a while. Close the lid. ",
      "7. Now adjust salt and sugar, crush some kasuri methi and add.",
      "8. Garnish with coriander leaves, ghee and serve."],
    imageUrl: "https://www.foodandwine.com/thmb/tAS-x_IC4ss1cb9EdDpsr0UExdM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/bucatini-with-mushroom-ragu-dandelion-greens-and-tarragon-FT-RECIPE0421-3a5f0d29f7264f5e9952d4a3a51f5f58.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
  Recipe(
    title: " Italian Spaghetti",
    description: ["1. In a large bowl, take boiled chickpeas and add yoghurt, ginger-garlic paste, fenugreek seeds, garam masala, turmeric powder, coriander powder, red chilli powder, chaat masala, black pepper powder, and salt. Mix well until the boiled chickpeas are coated well. Cover the bowl and keep it aside for 30 minutes to 1 hour.",
      "2. In a pan, put some oil/butter, and add ginger-garlic paste to it. Now dump the solid spices into the cooked ginger-garlic paste. After they begin to pop, add chopped onions and cook them until they are translucent.",
      "3. Now put the chopped tomatoes in the pan. Add rest of the spices – cumin powder, garam masala, turmeric powder, soaked cashews, coriander powder, red chilli powder, and salt. Mix well and cover the lid so that the tomatoes become soft and mushy. Switch off the gas burner and let the mixture cool down.",
      "4. In another pan, take some oil/butter and add the marinated chole. Cook them until they start to smell aromatic. Put off the burner.",
      "5. Now, put the onion-tomato paste in a mixer and blend until it becomes smooth like a paste. Be careful that the blender does not overheat because of the hot onion-tomato mix. Keep opening the lid to let off the steam.",
      "6. After the paste is ready, add this to the pan of marinated chickpeas. At this point, you will have to decide the thickness of the gravy. Add one 1.5 cups of water and mix everything. Bring it to boil.",
      "7. Make sure to taste the gravy at this point. Add spices to adjust the taste levels. Now add 1 cup of heavy cream in the chickpea tikka masala. Mix well.",
      "8. Garnish the chickpea tikka masala with coriander and ginger slivers. And voila! your Chickpea Tikka Masala is ready to serve!"],
    imageUrl: "https://assets.unileversolutions.com/v1/84326391.jpg",
      ingredients: ["300 gms Carrot Skin Peel",
        "300 Beetroot Skin Peel",
        "125 Mava125",
        "Sugar25 ",
        "Desi Ghee",
        "15 Cashewnuts",
        "1 Cardamom Powder",
        "10 Raisin",
        "7 Almond Flakes",
        "50 Milk"]),
];

